### ISSUE TITLE
Having trouble triggering Backbone collection events

### ISSUE THREAD

**Issue by jamesfacts** [jamesfacts/yah_app#1]
I'm attempting to access a Backbone view and swap change it's collection from one collection to another. This collection has a listener set that looks for a 'reset' event, which should trigger a render event.

I can successfully create the new collection and assign it to the view. When I check the collection property of my view through the console, I see the correct, new, view assigned. When I fetch the data in the new collection, the data populates models in my new collection, but fails to trigger the listener. Worse... if I try to iterate through the collection myself, I get an error trying to do anything "each" or "for-each" on the collection. 

What I've tried:
************************
-Googling
-Experimenting in the console
-StackOverflow.

A hand checking my process, perhaps? I'm stumped. 

Thanks!
James

@bigtone1284 @WilliamfShaw

**Comment by bigtone1284** [comment]
taken @WilliamfShaw  @h4w5

**Comment by jamesfacts** [comment]
Hey @bigtone1284 - here's what I ended up doing.  Gets the job done, but doesn't make use of any listeners.

I'll close the issue out, but if you have any brainstorms I'm eager to do this a better way.

```
var clickedUser = parseInt(clickInput.currentTarget.dataset.user);

// I instantiate the collection without passing any 'initialize' values, to stop it from fetching itself
App.singleUserQuestions = new App.Collections.SingleUserQuestions();

// Here I set the user manually through a function of the collection
App.singleUserQuestions.setQuestionUser(clickedUser);

// messy, but this seems to get the job done - after fetching, re-render the collection list view 
App.singleUserQuestions.fetch({success: function(){			
	this.parent.collection.set(App.singleUserQuestions.toJSON());
	this.parent.renderAllQuestions();
}.bind(this)})
```
